spring.application.name=demo

spring.datasource.url=jdbc:mysql://localhost:3306/Moon
spring.datasource.username=root
spring.datasource.password=hook040101

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true


spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
gemini.api-key=${GEMINI_API_KEY}
